# Docker Compose para build direto no Portainer
# Use este arquivo se quiser fazer build da aplicação no próprio servidor

version: '3.8'

services:
  poc-langchain:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: poc-langchain-app
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - poc-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.poc-langchain.rule=Host(`seu-dominio.com`)"
      - "traefik.http.services.poc-langchain.loadbalancer.server.port=3000"

networks:
  poc-network:
    driver: bridge
    name: poc-network