# Stack do Portainer para POC LangChain
# Cole este conteúdo na seção "Web editor" do Portainer

version: '3.8'

services:
  poc-langchain:
    image: node:18-alpine
    container_name: poc-langchain-app
    restart: unless-stopped
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
      # Configure as variáveis abaixo na seção Environment variables do Portainer
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      # Monte o código fonte via volume ou use imagem já buildada
      - /path/to/your/project:/app
    command: |
      sh -c "
        apk add --no-cache curl &&
        npm ci --only=production &&
        npm run build &&
        npm start
      "
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - poc-network
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  # Opcional: Nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: poc-langchain-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - poc-langchain
    volumes:
      - nginx_config:/etc/nginx/conf.d
    networks:
      - poc-network
    profiles:
      - production

networks:
  poc-network:
    driver: bridge

volumes:
  nginx_config:
    driver: local